config_version = 14

[bar.default]
center = ["workspaces"]
end = [
    "tray",
    "media",
    "volume",
    "brightness",
    "battery",
    "network",
    "bluetooth",
    "notifications",
    "caffeine",
    "clipboard",
    "control-center",
    "session",
]
margin_ends = 0
radius = 0
scale = 0.80000000447034836
start = ["launcher", "wallpaper", "clock", "cpu", "ram", "privacy"]
thickness = 24

[calendar]

[control_center.calendar]
show_events_card = false
show_week_numbers = true

[control_center]
width = 1000

[dock]
cross_axis_padding = 6
icon_size = 24
launcher_position = "start"
layer = "overlay"
main_axis_padding = 8
margin_edge = 8
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners]
enabled = true

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]
pre_action_fade_seconds = 10

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 300.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = false
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = false
timeout = 660.0

[lockscreen]
blur_intensity = 0.0
tint_intensity = 0.0

[shell]
polkit_agent = true
app_icon_color = "on_surface"
app_icon_colorize = false
screen_time_enabled = true

[shell.panel]
control_center_placement = "floating"
control_center_position = "center"

[theme]
community_palette = "GitHub Dark"
pure_black_dark = true
source = "community"

[theme.templates]
builtin_ids = [
    "btop",
    "gtk3",
    "gtk4",
    "ghostty",
    "kcolorscheme",
    "niri",
    "qt",
    "sway",
]
community_ids = ["claude-code", "pywalfox", "discord", "prismlauncher"]

[widget.clock]
format = "{:%H:%M} {:%a} {:%d.%m.%y}"

[widget.cpu]
show_glyph = false
visualization = "graph"

[widget.network]
vpn_status = "both"

[widget.ram]
show_glyph = false
visualization = "graph"

[widget.wallpaper]
enabled = false

[widget.tray]
hide_passive = false

[widget.workspaces]
empty_color = "on_surface"
focused_output_only = true
occupied_color = "on_surface"
show_all_outputs = true
style = "minimal"
